/* Native line + English translation per voice hit (from voice2.py LINES). */
window.HIT_TEXT = {
  "pt": ["Anota aí: reunião amanhã às três com o cliente.", "Meeting tomorrow at three with the client."],
  "es": ["Escribe un correo a mi jefe, en inglés.", "Write an email to my boss, in English."],
  "fr": ["Écris un message pour dire que je suis en retard.", "Running late — write them a message."],
  "de": ["Schreib eine E-Mail an den Kunden, bitte auf Englisch.", "Email the client, please in English."],
  "it": ["Scrivi una nota: comprare il pane domani.", "Note: buy bread tomorrow."],
  "ru": ["Напиши письмо клиенту, пожалуйста.", "Please write to the client."],
  "zh": ["把这段话翻译成英文。", "Translate this into English."],
  "ja": ["明日の会議のメモを書いて。", "Write up tomorrow's meeting notes."],
  "ko": ["이메일을 영어로 써 줘.", "Write the email in English."],
  "nl": ["Schrijf een bericht naar de klant.", "Message the customer."],
  "pl": ["Napisz wiadomość do klienta.", "Message the client."],
  "tr": ["Müşteriye bir e-posta yaz.", "Email the customer."],
  "uk": ["Напиши лист клієнту.", "Write to the client."],
  "hi": ["यह बात अंग्रेज़ी में लिखो।", "Write this in English."],
  "ar": ["اكتب رسالة إلى العميل.", "Message the client."],
  "id": ["Tulis pesan untuk klien.", "Message the client."],
  "vi": ["Viết tin nhắn cho khách hàng.", "Message the customer."],
  "ro": ["Scrie un mesaj clientului.", "Message the client."],
  "el": ["Γράψε ένα μήνυμα στον πελάτη.", "Message the customer."],
  "sv": ["Skriv ett meddelande till kunden.", "Message the customer."],
  "cs": ["Napiš zprávu klientovi.", "Message the client."],
  "hu": ["Írj üzenetet az ügyfélnek.", "Message the client."],
  "th": ["เขียนข้อความถึงลูกค้า", "Message the customer."],
  "ur": ["کلائنٹ کو پیغام لکھو۔", "Message the client."],
  "en1": ["Reply to Maria: there in twenty minutes.", "English, as spoken."],
  "en2": ["Add a note: invoice the client Friday.", "English, as spoken."]
};
