# -*- coding: utf-8 -*-
"""Swarm D: AR HI UR TR RO SV."""
LANG_D = {
    "ar": {
        "voiceM": "ar-SA-HamedNeural", "voiceF": "ar-SA-ZariyahNeural",
        "hook": "رأيت خطأ؟ عندك فكرة؟ علّق الآن!",
        "cta_full": "كلماتك تبني supEars",
        "cta_m": "كلماتك تبني،",
        "cats": "خطأ، نقد، اقتراح أو ثناء.",
        "chips": ["خطأ", "نقد", "اقتراح", "ثناء"],
        "how": "اترك تعليقك بالأسفل",
        "testi": "هذه الأذن تترجم وتكتب كل ما أقوله!",
        "howcard": "تعليقك هنا!",
        "date": "الإصدار · 10 أكتوبر 2026",
        "speak_sub": "تكلّم بحرية! الرابط بالأسفل.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@mariam.tasma",
    },
    "hi": {
        "voiceM": "hi-IN-MadhurNeural", "voiceF": "hi-IN-SwaraNeural",
        "hook": "कोई बग देखा? कोई आइडिया है? कमेंट करें!",
        "cta_full": "आपके शब्द बनाते हैं supEars",
        "cta_m": "आपके शब्द बनाते हैं,",
        "cats": "बग, आलोचना, सुझाव या तारीफ़।",
        "chips": ["बग", "आलोचना", "सुझाव", "तारीफ़"],
        "how": "अपनी टिप्पणी नीचे छोड़ें",
        "testi": "यह कान मेरी हर बात का अनुवाद करता है और लिख लेता है!",
        "howcard": "आपकी टिप्पणी यहाँ!",
        "date": "रिलीज़ · 10 अक्टूबर 2026",
        "speak_sub": "खुलकर बोलें! लिंक नीचे है।",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@meera.sunti",
    },
    "ur": {
        "voiceM": "ur-PK-AsadNeural", "voiceF": "ur-PK-UzmaNeural",
        "hook": "بگ دیکھا؟ کوئی آئیڈیا ہے؟ کمنٹ کریں!",
        "cta_full": "آپ کے الفاظ بناتے ہیں supEars",
        "cta_m": "آپ کے الفاظ بناتے ہیں،",
        "cats": "بگ، تنقید، تجویز یا تعریف۔",
        "chips": ["بگ", "تنقید", "تجویز", "تعریف"],
        "how": "اپنا کمنٹ نیچے چھوڑیں",
        "testi": "یہ کان میری ہر بات کا ترجمہ کرتا ہے اور لکھ لیتا ہے!",
        "howcard": "آپ کا کمنٹ یہاں!",
        "date": "ریلیز · 10 اکتوبر 2026",
        "speak_sub": "کھل کر بولیں! لنک نیچے ہے۔",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maham.sunti",
    },
    "tr": {
        "voiceM": "tr-TR-AhmetNeural", "voiceF": "tr-TR-EmelNeural",
        "hook": "Hata mı gördün? Fikrin mi var? Yorum yap!",
        "cta_full": "Sözlerinle büyüyor supEars",
        "cta_m": "Sözlerinle büyüyor,",
        "cats": "Hata, eleştiri, öneri veya övgü.",
        "chips": ["HATA", "ELEŞTİRİ", "ÖNERİ", "ÖVGÜ"],
        "how": "Yorumunu aşağıya bırak",
        "testi": "Bu kulak her dediğimi çeviriyor ve yazıyor!",
        "howcard": "Yorumun burada!",
        "date": "Çıkış · 10 Ekim 2026",
        "speak_sub": "Özgürce konuş! Bağlantı aşağıda.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@meryem.duyar",
    },
    "ro": {
        "voiceM": "ro-RO-EmilNeural", "voiceF": "ro-RO-AlinaNeural",
        "hook": "Ai văzut un bug? Ai o idee? Comentează!",
        "cta_full": "Cuvintele tale construiesc supEars",
        "cta_m": "Cuvintele tale construiesc,",
        "cats": "Bug, critică, sugestie sau laudă.",
        "chips": ["BUG", "CRITICĂ", "SUGESTIE", "LAUDĂ"],
        "how": "Lasă-ți comentariul mai jos",
        "testi": "Urechea asta traduce și scrie tot ce spun!",
        "howcard": "Comentariul tău aici!",
        "date": "Lansare · 10 octombrie 2026",
        "speak_sub": "Vorbește liber! Linkul e mai jos.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.aude",
    },
    "sv": {
        "voiceM": "sv-SE-MattiasNeural", "voiceF": "sv-SE-SofieNeural",
        "hook": "Hittat en bugg? Fått en idé? Kommentera!",
        "cta_full": "Dina ord bygger supEars",
        "cta_m": "Dina ord bygger,",
        "cats": "Bugg, kritik, förslag eller beröm.",
        "chips": ["BUGG", "KRITIK", "FÖRSLAG", "BERÖM"],
        "how": "Lämna din kommentar nedan",
        "testi": "Det här örat översätter och skriver allt jag säger!",
        "howcard": "Din kommentar här!",
        "date": "Release · 10 oktober 2026",
        "speak_sub": "Prata fritt! Länken finns nedan.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.hor",
    },
}
