# -*- coding: utf-8 -*-
"""Swarm C: ZH JA KO VI TH ID."""
LANG_C = {
    "zh": {
        "voiceM": "zh-CN-YunxiNeural", "voiceF": "zh-CN-XiaoxiaoNeural",
        "hook": "发现 Bug？有想法？快来评论！",
        "cta_full": "你的每一句话，都在打造 supEars",
        "cta_m": "你的每一句话，都在打造，",
        "cats": "Bug，批评，建议或表扬。",
        "chips": ["Bug", "批评", "建议", "表扬"],
        "how": "在下方留下你的评论吧",
        "testi": "这只耳朵会写下我说的一切！",
        "howcard": "你的评论在这里！",
        "date": "发布 · 2026年10月10日",
        "speak_sub": "畅所欲言！链接在下方。",
    },
    "ja": {
        "voiceM": "ja-JP-KeitaNeural", "voiceF": "ja-JP-NanamiNeural",
        "hook": "バグを見つけた？アイデアがある？コメントしよう！",
        "cta_full": "あなたの言葉がつくる supEars",
        "cta_m": "あなたの言葉がつくる、",
        "cats": "Bug、批判、提案、称賛。",
        "chips": ["Bug", "批判", "提案", "称賛"],
        "how": "下にコメントを残そう",
        "testi": "この耳は私の言うことを全部書いてくれる！",
        "howcard": "あなたのコメントはこちら！",
        "date": "リリース · 2026年10月10日",
        "speak_sub": "自由に話そう！リンクは下に。",
    },
    "ko": {
        "voiceM": "ko-KR-InJoonNeural", "voiceF": "ko-KR-SunHiNeural",
        "hook": "버그를 찾았나요? 아이디어가 있나요? 댓글을 남겨주세요!",
        "cta_full": "여러분의 말이 만드는 supEars",
        "cta_m": "여러분의 말이 만드는,",
        "cats": "Bug, 비판, 제안 또는 칭찬.",
        "chips": ["Bug", "비판", "제안", "칭찬"],
        "how": "아래에 댓글을 남겨주세요",
        "testi": "이 귀가 제가 말하는 걸 다 적어줘요!",
        "howcard": "여러분의 댓글을 여기에!",
        "date": "출시 · 2026년 10월 10일",
        "speak_sub": "자유롭게 말하세요! 링크는 아래에.",
    },
    "vi": {
        "voiceM": "vi-VN-NamMinhNeural", "voiceF": "vi-VN-HoaiMyNeural",
        "hook": "Thấy lỗi? Có ý tưởng? Hãy bình luận nhé!",
        "cta_full": "Lời của bạn tạo nên supEars",
        "cta_m": "Lời của bạn tạo nên,",
        "cats": "Bug, phê bình, góp ý hoặc khen.",
        "chips": ["Bug", "phê bình", "góp ý", "khen"],
        "how": "Hãy để lại bình luận bên dưới",
        "testi": "Chiếc tai này viết lại mọi điều tôi nói!",
        "howcard": "Bình luận của bạn ở đây!",
        "date": "Phát hành · 10 tháng 10, 2026",
        "speak_sub": "Hãy nói tự do! Link ở bên dưới.",
    },
    "th": {
        "voiceM": "th-TH-NiwatNeural", "voiceF": "th-TH-PremwadeeNeural",
        "hook": "เจอบั๊กไหม? มีไอเดียไหม? คอมเมนต์เลย!",
        "cta_full": "คำพูดของคุณสร้าง supEars",
        "cta_m": "คำพูดของคุณสร้าง,",
        "cats": "บั๊ก, ติชม, ข้อเสนอ หรือ คำชม.",
        "chips": ["บั๊ก", "ติชม", "ข้อเสนอ", "คำชม"],
        "how": "ฝากคอมเมนต์ไว้ด้านล่าง",
        "testi": "หูนี้เขียนทุกอย่างที่ฉันพูดเลย!",
        "howcard": "คอมเมนต์ของคุณตรงนี้!",
        "date": "เปิดตัว · 10 ตุลาคม 2026",
        "speak_sub": "พูดได้เต็มที่! ลิงก์อยู่ด้านล่าง.",
    },
    "id": {
        "voiceM": "id-ID-ArdiNeural", "voiceF": "id-ID-GadisNeural",
        "hook": "Lihat bug? Punya ide? Tulis komentar!",
        "cta_full": "Kata Anda membangun supEars",
        "cta_m": "Kata Anda membangun,",
        "cats": "Bug, kritik, saran atau pujian.",
        "chips": ["Bug", "kritik", "saran", "pujian"],
        "how": "Tulis komentar Anda di bawah",
        "testi": "Telinga ini menulis semua yang saya katakan!",
        "howcard": "Komentar Anda di sini!",
        "date": "Rilis · 10 Oktober 2026",
        "speak_sub": "Bicara bebas! Tautan di bawah.",
    },
}
