# -*- coding: utf-8 -*-
"""Swarm A: ES FR DE IT NL EN."""
LANG_A = {
    "es": {
        "voiceM": "es-ES-AlvaroNeural", "voiceF": "es-ES-ElviraNeural",
        "hook": "¿Encontraste un error? ¿Tienes una idea? ¡Comenta!",
        "cta_full": "Tus palabras crean supEars",
        "cta_m": "Tus palabras crean,",
        "cats": "Error, crítica, sugerencia o elogio.",
        "chips": ["ERROR", "CRÍTICA", "SUGERENCIA", "ELOGIO"],
        "how": "Deja tu comentario abajo",
        "testi": "¡Esta oreja traduce y escribe todo lo que digo!",
        "howcard": "¡Tu comentario aquí!",
        "date": "Lanzamiento · 10 de octubre de 2026",
        "speak_sub": "¡Habla libremente! Enlace abajo.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.escucha",
    },
    "fr": {
        "voiceM": "fr-FR-HenriNeural", "voiceF": "fr-FR-DeniseNeural",
        "hook": "Un bug ? Une idée ? Commentez !",
        "cta_full": "Vos mots construisent supEars",
        "cta_m": "Vos mots construisent,",
        "cats": "Bug, critique, suggestion ou compliment.",
        "chips": ["BUG", "CRITIQUE", "SUGGESTION", "COMPLIMENT"],
        "how": "Laissez votre commentaire ci-dessous",
        "testi": "Cette oreille traduit et écrit tout ce que je dis !",
        "howcard": "Votre commentaire ici !",
        "date": "Sortie · 10 octobre 2026",
        "speak_sub": "Parlez librement ! Lien ci-dessous.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@marie.ecoute",
    },
    "de": {
        "voiceM": "de-DE-ConradNeural", "voiceF": "de-DE-KatjaNeural",
        "hook": "Fehler gefunden? Idee? Kommentiere!",
        "cta_full": "Deine Worte bauen supEars",
        "cta_m": "Deine Worte bauen,",
        "cats": "Bug, Kritik, Vorschlag oder Lob.",
        "chips": ["BUG", "KRITIK", "VORSCHLAG", "LOB"],
        "how": "Schreib unten deinen Kommentar",
        "testi": "Dieses Ohr übersetzt und schreibt alles auf, was ich sage!",
        "howcard": "Dein Kommentar hier!",
        "date": "Release · 10. Oktober 2026",
        "speak_sub": "Sprich frei! Link unten.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.hoert",
    },
    "it": {
        "voiceM": "it-IT-DiegoNeural", "voiceF": "it-IT-ElsaNeural",
        "hook": "Hai trovato un bug? Hai un'idea? Commenta!",
        "cta_full": "Le tue parole creano supEars",
        "cta_m": "Le tue parole creano,",
        "cats": "Bug, critica, consiglio o elogio.",
        "chips": ["BUG", "CRITICA", "CONSIGLIO", "ELOGIO"],
        "how": "Lascia il tuo commento qui sotto",
        "testi": "Questo orecchio traduce e scrive tutto quello che dico!",
        "howcard": "Il tuo commento qui!",
        "date": "Uscita · 10 ottobre 2026",
        "speak_sub": "Parla liberamente! Link qui sotto.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.ascolta",
    },
    "nl": {
        "voiceM": "nl-NL-MaartenNeural", "voiceF": "nl-NL-ColetteNeural",
        "hook": "Een bug gespot? Een idee? Reageer!",
        "cta_full": "Jouw woorden bouwen supEars",
        "cta_m": "Jouw woorden bouwen,",
        "cats": "Bug, kritiek, suggestie of compliment.",
        "chips": ["BUG", "KRITIEK", "SUGGESTIE", "COMPLIMENT"],
        "how": "Laat hieronder je reactie achter",
        "testi": "Dit oor vertaalt en schrijft alles op wat ik zeg!",
        "howcard": "Jouw reactie hier!",
        "date": "Release · 10 oktober 2026",
        "speak_sub": "Spreek vrij! Link hieronder.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.luistert",
    },
    "en": {
        "voiceM": "en-US-GuyNeural", "voiceF": "en-US-AriaNeural",
        "hook": "Spotted a bug? Got an idea? Comment!",
        "cta_full": "Your words build supEars",
        "cta_m": "Your words build,",
        "cats": "Bug, critique, suggestion or praise.",
        "chips": ["BUG", "CRITIQUE", "SUGGESTION", "PRAISE"],
        "how": "Leave your comment below",
        "testi": "This ear translates and writes everything I say!",
        "howcard": "Your comment here!",
        "date": "Release · October 10, 2026",
        "speak_sub": "Speak freely! Link below.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@mary.hears",
    },
}
