# -*- coding: utf-8 -*-
"""Swarm B: RU UK PL CS HU EL."""
LANG_B = {
    "ru": {
        "voiceM": "ru-RU-DmitryNeural", "voiceF": "ru-RU-SvetlanaNeural",
        "hook": "Нашли ошибку? Есть идея? Пишите!",
        "cta_full": "Ваши слова создают supEars",
        "cta_m": "Ваши слова создают,",
        "cats": "Баг, критика, идея или похвала.",
        "chips": ["БАГ", "КРИТИКА", "ИДЕЯ", "ПОХВАЛА"],
        "how": "Оставьте комментарий ниже!",
        "testi": "Это ухо переводит и записывает всё, что я говорю!",
        "howcard": "Ваш комментарий здесь!",
        "date": "Релиз · 10 октября 2026",
        "speak_sub": "Говорите свободно! Ссылка ниже.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@masha.slyshit",
    },
    "uk": {
        "voiceM": "uk-UA-OstapNeural", "voiceF": "uk-UA-PolinaNeural",
        "hook": "Помітили баг? Є ідея? Коментуйте!",
        "cta_full": "Ваші слова створюють supEars",
        "cta_m": "Ваші слова створюють,",
        "cats": "Баг, критика, ідея або похвала.",
        "chips": ["БАГ", "КРИТИКА", "ІДЕЯ", "ПОХВАЛА"],
        "how": "Залиште коментар нижче!",
        "testi": "Це вухо перекладає і записує все, що я кажу!",
        "howcard": "Ваш коментар тут!",
        "date": "Реліз · 10 жовтня 2026",
        "speak_sub": "Говоріть вільно! Посилання нижче.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@marichka.chuye",
    },
    "pl": {
        "voiceM": "pl-PL-MarekNeural", "voiceF": "pl-PL-ZofiaNeural",
        "hook": "Znalazłeś błąd? Masz pomysł? Komentuj!",
        "cta_full": "Twoje słowa budują supEars",
        "cta_m": "Twoje słowa budują,",
        "cats": "Błąd, krytyka, propozycja lub pochwała.",
        "chips": ["BŁĄD", "KRYTYKA", "PROPOZYCJA", "POCHWAŁA"],
        "how": "Zostaw komentarz poniżej!",
        "testi": "To ucho tłumaczy i zapisuje wszystko, co mówię!",
        "howcard": "Twój komentarz tutaj!",
        "date": "Premiera · 10 października 2026",
        "speak_sub": "Mów swobodnie! Link poniżej.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.slyszy",
    },
    "cs": {
        "voiceM": "cs-CZ-AntoninNeural", "voiceF": "cs-CZ-VlastaNeural",
        "hook": "Našli jste chybu? Máte nápad? Komentujte!",
        "cta_full": "Vaše slova tvoří supEars",
        "cta_m": "Vaše slova tvoří,",
        "cats": "Chyba, kritika, návrh nebo pochvala.",
        "chips": ["CHYBA", "KRITIKA", "NÁVRH", "POCHVALA"],
        "how": "Zanechte komentář níže!",
        "testi": "Toto ucho překládá a zapisuje vše, co říkám!",
        "howcard": "Váš komentář zde!",
        "date": "Vydání · 10. října 2026",
        "speak_sub": "Mluvte svobodně! Odkaz níže.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@marie.slysi",
    },
    "hu": {
        "voiceM": "hu-HU-TamasNeural", "voiceF": "hu-HU-NoemiNeural",
        "hook": "Hibát találtál? Van ötleted? Kommentelj!",
        "cta_full": "Szavaid építik supEars",
        "cta_m": "Szavaid építik,",
        "cats": "Hiba, kritika, javaslat vagy dicséret.",
        "chips": ["HIBA", "KRITIKA", "JAVASLAT", "DICSÉRET"],
        "how": "Írj kommentet alább!",
        "testi": "Ez a fül lefordít és leír mindent, amit mondok!",
        "howcard": "Kommented itt!",
        "date": "Megjelenés · 2026. október 10.",
        "speak_sub": "Beszélj szabadon! Link alul.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.hallja",
    },
    "el": {
        "voiceM": "el-GR-NestorasNeural", "voiceF": "el-GR-AthinaNeural",
        "hook": "Βρήκες σφάλμα; Έχεις ιδέα; Σχολίασε!",
        "cta_full": "Τα λόγια σου χτίζουν supEars",
        "cta_m": "Τα λόγια σου χτίζουν,",
        "cats": "Σφάλμα, κριτική, πρόταση ή έπαινος.",
        "chips": ["ΣΦΑΛΜΑ", "ΚΡΙΤΙΚΗ", "ΠΡΟΤΑΣΗ", "ΕΠΑΙΝΟΣ"],
        "how": "Άφησε το σχόλιό σου παρακάτω!",
        "testi": "Αυτό το αυτί μεταφράζει και γράφει ό,τι λέω!",
        "howcard": "Το σχόλιό σου εδώ!",
        "date": "Κυκλοφορία · 10 Οκτωβρίου 2026",
        "speak_sub": "Μίλα ελεύθερα! Σύνδεσμος παρακάτω.",
        "testi_en": "This ear translates and writes everything I say!",
        "name": "@maria.akouei",
    },
}
